#!/usr/bin/env bash

echo "Building library ${1}..."
START=$(node -e 'console.log(new Date().getTime())')

# build the lib
ng build $1

END=$(node -e 'console.log(new Date().getTime())')
DUR=$((( END - START )))
echo "Library built in ${DUR}ms."
