#!/usr/bin/env bash

START=$(node -e 'console.log(new Date().getTime())')
DEMONAME="${1}-demo"

# build the demo
ng build $DEMONAME  --prod --aot --baseHref "/ngx-libs/${1}/"

# move the files...
mv dist/$DEMONAME/* docs/$1/
rm -rf dist/$DEMONAME

END=$(node -e 'console.log(new Date().getTime())')
DUR=$((( END - START )))
echo "Demo built in ${DUR}ms."
