#!/usr/bin/env node
const fs = require('fs-extra');
const path = require('path');
const marked = require('marked')



fs.readFile(path.join(process.cwd(), 'README.md'))
  .then((result) => {

    const insides = marked(result.toString());
    const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>@nowzoo/ngx-libs</title>
  </head>
  <body>
    <div class="container my-4">
      ${insides}
    </div>
  </body>
</html>`;
    return fs.outputFile(path.join(process.cwd(), 'docs', 'index.html'), html);
  });
