#!/usr/bin/env bash



# docs...

START=$(node -e 'console.log(new Date().getTime())')
echo "Building docs for library ${1}..."
# go to lib folder
cd projects/$1
# get the version...
VERSION=$(node -p "require('./package.json').version")
# build the docs...
compodoc  -p tsconfig.lib.json  \
  --disableCoverage --disablePrivate \
  --disableProtected --disableLifeCycleHooks \
  --output "../../docs/${1}/docs" -n "@nowzoo/${1} ${VERSION} Documentation"
cd ../..
END=$(node -e 'console.log(new Date().getTime())')
DUR=$((( END - START )))
echo "Docs built in ${DUR}ms."
